version: '3'
services:
  xxl-job:
    image: xuxueli/xxl-job-admin:2.3.0
    container_name: xxl-job
    ports:
      - "8085:8080"
    environment:
      PARAMS: '--spring.datasource.url=jdbc:mysql://192.168.33.10:3306/xxl_job?Unicode=true&characterEncoding=UTF-8 --spring.datasource.username=root  --spring.datasource.password=Pass_123'
    restart: always
